apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: guestbook-rule
  namespace: guestbook-app
spec:
  clusterConditions:
  - type: OK
  clusterSelector:
    matchExpressions: []
    matchLabels:
      purpose: dev-b
